import { Oswald } from "next/font/google";
import "./globals.css";
import Header from "../components/shared/Header";
import Footer from "../components/shared/Footer";
import CartProvider from "../context/CartContext";
import NextTopLoader from "nextjs-toploader";

const font = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Camera Store",
  description: "Generated by Maro Asam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={font.className}>
          <Header />
          <NextTopLoader 
            color="#E21818"
            showSpinner={true}
            
          />
          {children}
          <Footer />
        </body>
      </CartProvider>
    </html>
  );
}
